name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: denoland/setup-deno@v2
        with:
          gleam-version: "1.16.0"
      - run: gleam deps download
      - run: gleam test --target javascript --runtime node
      - run: gleam test --target javascript --runtime deno
      - run: gleam test --target javascript --runtime bun
      - run: gleam format --check src test
