name = "etch_javascript"
version = "1.0.0"
description = "A Gleam TUI Backend Library"
licences = ["MIT"]
repository = { type = "github", user = "bananaofhappiness", repo = "etch" }
target = "javascript"

# [javascript]
# runtime = "bun"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
# etch = ">= 1.4.0 and < 2.0.0"
etch = { path = ".." }
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
